#!/usr/bin/env python3
"""Generate the Falcon experiment YAML for a given driver revision.

Keeps the driver source and the manifest byte-identical by construction, and
removes the baseline-005 retry hazard: recovering *previous* runs' artifacts is
no longer a prerequisite for the business run.

Usage:
  python3 research/software-stack/tools/make_falcon_yaml.py --index 006 --output deploy/falcon/sglang-v7-driver-006.yaml
"""

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
DRIVER = ROOT / 'research/software-stack/tools/sglang_v7_driver.py'
PROBE = ROOT / 'research/software-stack/tools/tpu_device_events_probe.py'


def indent(text, prefix):
    return '\n'.join(prefix + line if line.strip() else '' for line in text.splitlines())


def build(index, purpose_note):
    driver = DRIVER.read_text()
    probe = PROBE.read_text()
    name = 'jax-source-analysis-sglang-v7-driver-' + index
    header = f'''# Qwen3-8B real checkpoint baseline via native prefill/decode; four physical v7x chips.
# Generated by research/software-stack/tools/make_falcon_yaml.py from the driver sources.
{'# ' + index + ': ' + purpose_note}
name: {name}
exp_type: TRAINING
artifact_type: GCS
config: '{{"purpose":"qwen3-real-baseline","source":"338c6622cfe929223c677e641a97ea62525720b7","physical_chips":4,"jax_devices":8,"VERSION-SKEW":true,"entry":"ModelRunner+ScheduleBatch"}}'
cluster_name: tpu-training-antgroup
priority: 0
role_to_task_spec:
  worker:
    command: |
'''

    body = []
    body.append("      cat > /tmp/sglang_v7_driver.py <<'DRIVER'")
    body.append(indent(driver, '      '))
    body.append('      DRIVER')
    body.append("      cat > /tmp/tpu_device_events_probe.py <<'REGION_PROBE'")
    body.append(indent(probe, '      '))
    body.append('      REGION_PROBE')
    body.append("      cat > /tmp/run-driver.sh <<'BOOTSTRAP'")
    body.append(indent(BOOTSTRAP.replace('__INDEX__', index), '      '))
    body.append('      BOOTSTRAP')
    body.append("      cat > /tmp/run-region.sh <<'REGIONBOOT'")
    body.append(indent(REGION_BOOTSTRAP, '      '))
    body.append('      REGIONBOOT')

    tail = '''
    replica: 1
    image: python:3.12
    device_count: 8
    device_type: v7x
    device_topo: 2x2x1
    envs:
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      JAX_PLATFORMS: tpu
      XLA_FLAGS: "--xla_dump_to=/tmp/jax-v7-driver/xla --xla_dump_hlo_as_text"
      HF_HOME: /tmp/huggingface
      JAX_COMPILATION_CACHE_DIR: /tmp/jax-cache
      XLA_PYTHON_CLIENT_PREALLOCATE: "false"
    mounts:
      - name: tops-pallas-kernel
        type: gcs
        bucket: tops-pallas_kernel
        mount_path: /root/tops-pallas_kernel
        read_only: false
        mount_options:
          - implicit-dirs
'''
    return header + '\n'.join(body) + '\n' + tail


# The business run. No dependency on any previous run's artifacts.
BOOTSTRAP = '''set -eu
ulimit -c 0
mkdir -p /tmp/jax-v7-driver /tmp/venv-check
trap 'rc=$?; printf "%s\\n" "$rc" > /tmp/jax-v7-driver/exit-code; mkdir -p /root/tops-pallas_kernel/jax-source-analysis/sglang-v7-driver-__INDEX__; cp -r /tmp/jax-v7-driver/. /root/tops-pallas_kernel/jax-source-analysis/sglang-v7-driver-__INDEX__/ 2>/dev/null || true; echo CAPTURE_READY_FOR_RETRIEVAL; sleep 300; exit "$rc"' EXIT
python3 -m pip install --no-cache-dir 'uv==0.12.9'
python3 - <<'FETCH'
import urllib.request, tarfile, hashlib
from pathlib import Path
url='https://codeload.github.com/sgl-project/sglang-jax/tar.gz/338c6622cfe929223c677e641a97ea62525720b7'
a=Path('/tmp/sglang.tar.gz')
with urllib.request.urlopen(url, timeout=180) as r: a.write_bytes(r.read())
Path('/tmp/jax-v7-driver/source-archive.sha256').write_text(hashlib.sha256(a.read_bytes()).hexdigest()+'\\n')
with tarfile.open(a) as t: t.extractall('/tmp/sglang-source', filter='data')
FETCH
uv pip install --system --no-cache 'jax[tpu]==0.8.1' 'libtpu==0.0.30' /tmp/sglang-source/sglang-jax-338c6622cfe929223c677e641a97ea62525720b7/python
python3 - <<'CHECK'
import hashlib
from pathlib import Path
p=Path('/tmp/sglang-source/sglang-jax-338c6622cfe929223c677e641a97ea62525720b7/python/sgl_jax/srt/models/qwen3.py')
got=hashlib.sha256(p.read_bytes()).hexdigest()
assert got == '4bf0b5f83c97b7c150170baf825923ca856571a488ee80720bef163583f5661c', got
print('QWEN3_SOURCE_PIN_OK', got, flush=True)
CHECK
# Cheap fail-fast: imports, CLI parsing, API-shape pins. No checkpoint, no compile.
timeout --signal=TERM --kill-after=30s 10m python3 /tmp/sglang_v7_driver.py \\
  --output /tmp/jax-v7-driver/preflight --preflight-only || {
    echo DRIVER_PREFLIGHT_FAILED; exit 3; }
echo DRIVER_PREFLIGHT_OK
# The real run. Incremental: writes progress after every case.
timeout --signal=TERM --kill-after=60s 90m python3 /tmp/sglang_v7_driver.py \\
  --output /tmp/jax-v7-driver/capture
echo DRIVER_COMPLETE
'''

# The device-region run, separate stack, separate stack lifetime, retrieved at once.
REGION_BOOTSTRAP = '''set -eu
ulimit -c 0
mkdir -p /tmp/jax-v7-region
python3 -m pip install --no-cache-dir 'uv==0.12.9'
uv venv --python 3.12 /tmp/jax-v7-region/venv
uv pip install --python /tmp/jax-v7-region/venv/bin/python --no-cache 'jax[tpu]==0.11.1' 'libtpu==0.0.46'
# Default and enabled captures, each its own fresh process, named scopes on.
env -u LIBTPU_INIT_ARGS /tmp/jax-v7-region/venv/bin/python /tmp/tpu_device_events_probe.py \\
  --output /tmp/jax-v7-region/device-events-default
printf '%s\\n' "$?" > /tmp/jax-v7-region/region-default.exit-code
LIBTPU_INIT_ARGS="--xla_enable_custom_call_region_trace=true --xla_xprof_register_llo_debug_info=true" \\
  /tmp/jax-v7-region/venv/bin/python /tmp/tpu_device_events_probe.py \\
  --output /tmp/jax-v7-region/device-events-enabled
printf '%s\\n' "$?" > /tmp/jax-v7-region/region-enabled.exit-code
tar -czf /tmp/jax-v7-region/region-captures.tar.gz -C /tmp/jax-v7-region \\
  device-events-default device-events-enabled region-default.exit-code region-enabled.exit-code
tar -tzf /tmp/jax-v7-region/region-captures.tar.gz > /tmp/jax-v7-region/region-captures.list
sha256sum /tmp/jax-v7-region/region-captures.tar.gz > /tmp/jax-v7-region/region-captures.sha256
base64 --wrap=1000 /tmp/jax-v7-region/region-captures.tar.gz > /tmp/jax-v7-region/region-captures.b64
mkdir -p /root/tops-pallas_kernel/jax-source-analysis/sglang-v7-region
cp -r /tmp/jax-v7-region/. /root/tops-pallas_kernel/jax-source-analysis/sglang-v7-region/
echo REGION_ARCHIVE_BEGIN
cat /tmp/jax-v7-region/region-captures.b64
echo REGION_ARCHIVE_END
echo REGION_ARCHIVE_DONE
'''


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--index', required=True)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--note', default='Qwen3-8B native prefill/decode baseline plus device region capture')
    args = parser.parse_args()
    text = build(args.index, args.note)
    args.output.write_text(text)
    print(f'wrote {args.output} ({len(text)} bytes)')


if __name__ == '__main__':
    main()
