"""Reviewed pinned-source anchors for dispatch, completion and host waits."""

LAYER = "Public PJRT execution and completion"
# id, component, path, anchor, min line, inputs, outputs, constraints
SITES = [
    ("jax.fastpath-gate", "jax", "jax/_src/pjit.py", "def _get_fastpath_data(", 190, "executable、effects、输出与 PGLE", "fastpath metadata 或 None", "ordered/unordered/ref effects、部分 PGLE/no_execution 和非 Array 输出等拒绝 fastpath；不能把所有 warm 调用统一画到 C++ 快路径。"),
    ("jax.execute-replicated", "jax", "jax/_src/interpreters/pxla.py", "  def __call__(self, *args):", 395, "Python 参数、输入/输出 handlers 与 effects", "结果 PyArray 与 token 注册", "ordered/unordered effects 或 host callbacks 时 with_tokens=True；否则默认不向 Python 返回完成 status。"),
    ("jax.pjit-fast-execute", "jax", "jaxlib/pjit.cc", "absl::StatusOr<nb::object> PjitFunction::Call(nb::handle callable,", 632, "Python 参数与缓存 executable", "包装 IFRT 输出的 PyArray", "满足 fastpath 条件后直接调用 IFRT Execute，未经过 PyLoadedExecutable::ExecuteSharded；返回 wrapper 不等于设备完成。"),
    ("jaxlib.execute-sharded", "jax", "jaxlib/py_executable.cc", "absl::StatusOr<PyExecuteResults> PyLoadedExecutable::ExecuteSharded(", 485, "PyArray、with_tokens、可选 launch_id", "PyExecuteResults", "fill_status=with_tokens；执行 stream 缺省取 host thread ID；不得外推 C API/provider 的实际调度。"),
    ("jaxlib.execute-local", "jax", "jaxlib/py_executable.cc", "absl::StatusOr<PyExecuteResults> ExecuteShardedOnLocalDevicesInternal(", 426, "IFRT executable、参数 shards、options", "输出与可选 ShardedToken/status", "检查每个参数的 addressable shard 数；释放 GIL 后调用 IFRT；同一个 IFRT joined status 可填入多个 token，不是再次拆分 native per-device future。"),
    ("ifrt.execute-options", "xla", "xla/python/ifrt/executable.h", "struct ExecuteOptions {", 125, "launch/donation/stream/status 配置", "IFRT 运行选项", "fill_status 只控制 ExecuteResult.status 的有效性；execution_stream_id 的接口合同不能证明每种 adapter 都完整转发。"),
    ("ifrt.execute-contract", "xla", "xla/python/ifrt/executable.h", "  virtual absl::StatusOr<ExecuteResult> Execute(", 317, "设备上的输入 Arrays、options、可选 devices", "ExecuteResult", "声明附近明确没有严格 barrier 语义；输入可用与输出 ready 的粒度由 backend 决定。"),
    ("ifrt.pjrt-execute", "xla", "xla/python/pjrt_ifrt/pjrt_executable.cc", "PjRtLoadedExecutable::Execute(absl::Span<ArrayRef> args,", 840, "PjRtCompatibleArray 列表与选项", "IFRT Array 输出及可选 joined status", "非 portable 分支始终请求 PJRT futures 并 JoinFutures，fill_status 只控制最终返回字段；不是对 TPU runtime 的实测。"),
    ("pjrt.c-execute-options", "xla", "xla/pjrt/c/pjrt_c_api.h", "struct PJRT_ExecuteOptions {", 1992, "调用选项与回调地址", "C ABI 字段", "此 pin 没有 execution_stream_id 字段；callback 函数寿命超过提交调用，call_location 指针只需覆盖调用。"),
    ("pjrt.c-execute-args", "xla", "xla/pjrt/c/pjrt_c_api.h", "struct PJRT_LoadedExecutable_Execute_Args {", 2051, "本地设备×参数列表、输出存储、可选完成事件", "buffer handles 与每设备完成事件", "输出列表由 caller 分配；输出 buffer/event 由 caller Destroy；调用直接报错时完成事件不会被填充。"),
    ("pjrt.capi-execute-args", "xla", "xla/pjrt/c_api_client/pjrt_c_api_client.cc", "PjRtCApiLoadedExecutable::GetCommonExecuteArgs(", 3273, "C++ PJRT buffers、options 与 backing storage", "PJRT_LoadedExecutable_Execute_Args", "映射 launch/non-donatable/callback 等；字段版本 gate 和 storage 生存期必须保留。"),
    ("pjrt.capi-execute", "xla", "xla/pjrt/c_api_client/pjrt_c_api_client.cc", "PjRtCApiLoadedExecutable::Execute(", 3412, "C++ inputs、options、可选 returned_futures", "C++ 输出 buffer 包装与 future", "经函数指针进入 plugin；本索引未证明 libtpu 使用开源 wrapper_impl；库调用 TraceMe 不是设备事件。"),
    ("pjrt.c-wrapper-execute", "xla", "xla/pjrt/c/pjrt_c_api_wrapper_impl.cc", "PJRT_Error* PJRT_LoadedExecutable_Execute(", 2313, "C Execute Args", "调用内层 C++ PJRT provider 后包装结果", "开源参考 adapter，仅 SOURCE-ONLY；不能无证据把它放进 libtpu.so 内部调用栈。"),
    ("pjrt.event-to-future", "xla", "xla/pjrt/c/pjrt_c_api_helpers.cc", "xla::Future<> ConvertCEventToCppFuture(PJRT_Event* c_event,", 374, "拥有的 PJRT_Event 与 API 表", "C++ future", "通过 OnReady 回调置 promise 并释放事件；注册失败分支另返错误 future，不能据成功分支宣称所有错误路径资源处理已验证。"),
    ("pjrt.event-ready-contract", "xla", "xla/pjrt/c/pjrt_c_api.h", "typedef PJRT_Error* PJRT_Event_IsReady(PJRT_Event_IsReady_Args* args);", 329, "PJRT_Event", "is_ready", "ready 包含错误完成；必须检查 Error 或 future status，不能等同数值成功。"),
    ("pjrt.event-callback-contract", "xla", "xla/pjrt/c/pjrt_c_api.h", "struct PJRT_Event_OnReady_Args {", 368, "event、callback、user_arg", "注册 ready callback 的参数", "回调接收并负责销毁 PJRT_Error；user_arg 所有权仍在 caller，不指定设备或回调执行线程。"),
    ("pjrt.buffer-ready-contract", "xla", "xla/pjrt/c/pjrt_c_api.h", "struct PJRT_Buffer_ReadyEvent_Args {", 2641, "PJRT_Buffer", "caller 拥有的 ready event", "数据 ready 或错误均触发；删除/捐赠与先取得 event 的时序有单独合同，不等同整个 executable 完成。"),
    ("pjrt.buffer-ready-event", "xla", "xla/pjrt/c_api_client/pjrt_c_api_client.cc", "PJRT_Event* PjRtCApiBuffer::GetReadyEvent() {", 3993, "buffer", "缓存的 PJRT_Buffer_ReadyEvent", "readiness_event_ 管理 C event 的寿命；与执行完成事件是不同 API 入口。"),
    ("pjrt.buffer-track-event", "xla", "xla/pjrt/c_api_client/pjrt_c_api_client.cc", "void PjRtCApiBuffer::MakePromiseTrackEvent() {", 4006, "readiness promise 与 event", "ready/error promise", "先 IsReady，已就绪则 Error 并立即 Set，否则 OnReady；不直接调用 PJRT_Event_Await。"),
    ("pjrt.buffer-ready-future", "xla", "xla/pjrt/c_api_client/pjrt_c_api_client.cc", "Future<> PjRtCApiBuffer::GetReadyFuture() {", 4060, "buffer 的删除状态与 readiness cache", "缓存的 C++ future 或错误", "删除/捐赠先拒绝；mutex 下只建立一次 promise，ready 不等同 status.ok。"),
    ("ifrt.array-ready", "xla", "xla/python/pjrt_ifrt/pjrt_array.cc", "tsl::Future<> PjRtArray::GetReadyFuture() const {", 616, "一个 IFRT Array 的本地 PJRT buffers", "一个或 JoinFutures 的 ready future", "只覆盖该 Array 所持 buffers，不是全设备/全进程 barrier。"),
    ("ifrt.values-ready", "xla", "xla/python/pjrt_ifrt/pjrt_client.cc", "tsl::Future<> PjRtClient::GetReadyFuture(absl::Span<const ValueRef> values) {", 1930, "若干 IFRT Value", "JoinFutures", "批量等待针对传入 values，不凭空加入其他计算或其他 host。"),
    ("jaxlib.array-wait", "jax", "jaxlib/py_array.cc", "absl::Status PyArray::BlockUntilReady() const {", 858, "一个 PyArray", "ready 或错误 status", "释放 GIL，调用 AwaitBuffersReady；本入口没有等同于整个运行的 result_status。"),
    ("jaxlib.buffers-wait", "jax", "jaxlib/util.cc", "absl::Status AwaitBuffersReady(absl::Span<ifrt::Array* const> ifrt_arrays) {", 56, "IFRT Arrays", "ready/status", "一个 array 直接取 GetReadyFuture；多个通过 client 批量取 future；随后等待并取 status。"),
    ("jaxlib.wait-with-signals", "jax", "jaxlib/util.cc", "void BlockUntilReadyWithCancel(xla::Future<>& future) {", 40, "一个 C++ Future", "host 等待或 Python 信号异常", "每 200 ms 检查 Python signals；本函数未调用设备 CancelExecution，名称中的 Cancel 不证明设备已取消。"),
    ("jaxlib.token-wait", "jax", "jaxlib/py_executable.cc", "absl::Status PyToken::Await() {", 118, "有效 execution status future", "等待后的 status", "释放 GIL Await，返回 Python 前展开 UserContext；不同于 output buffer ready。"),
    ("jaxlib.sharded-token-wait", "jax", "jaxlib/py_executable.cc", "absl::Status PyShardedToken::Await() {", 141, "一组 future", "等待全部后的合成 status", "本 Python adapter 可把同一个 IFRT joined status 复制到多个 token，不能据 token 个数推导独立设备计时。"),
    ("jax.effects-barrier", "jax", "jax/_src/api.py", "def effects_barrier():", 2747, "当前线程的 runtime_tokens", "等待已记录 effects", "runtime_tokens 为 threading.local；不是跨线程/跨 host 的通用 barrier。"),
    ("jax.runtime-tokens", "jax", "jax/_src/dispatch.py", "class RuntimeTokenSet(threading.local):", 115, "线程局部 effect/runtime token", "按 effect/device 保存 token", "block_until_ready 等待后清空当前线程记录；不能保证其他线程的 token 被看到。"),
    ("jax.block-until-ready", "jax", "jax/_src/api.py", "def block_until_ready(x):", 2751, "pytree 的 leaves", "同结构、所选 JAX array leaves ready", "单 Array 或批量分支；不把未传入的工作自动纳入等待范围。"),
    ("pjrt.profiler-link", "xla", "xla/pjrt/c/pjrt_c_api_helpers.cc", "PJRT_Profiler_Extension CreatePjrtProfilerExtension(", 1055, "库调用 trace 名称", "带 context ID 的 Profiler extension", "短生命周期 TraceMeProducer 使用 kPjrtLibraryCall=14；不是 kernel 区间，也未由此前仅支持 0/15 的 matcher 验证。"),
    ("pjrt.profiler-context", "xla", "xla/pjrt/c/pjrt_c_api_helpers.h", "int64_t GetTracemeContextId(InputType* args) {", 328, "API 或 Args 的 extension 链", "context ID，缺失时 -1", "调用方读取 API extension 与传给 plugin 的 Args extension 必须区分；缺失 ID 不能当作唯一关联。"),
]
SITES = [(i, c, LAYER, p, a, line, inp, out, limit) for i,c,p,a,line,inp,out,limit in SITES]
IDS = {s[0] for s in SITES}
EDGES = [
    ("jax.execute-replicated", "jaxlib.execute-sharded", "        results = self.xla_executable.execute_sharded(input_bufs, with_tokens=True)", "interface", "Python effect/host-callback 分支。"),
    ("jax.execute-replicated", "jaxlib.execute-sharded", "        results = self.xla_executable.execute_sharded(input_bufs)", "interface", "Python 无 effect 分支。"),
    ("jax.pjit-fast-execute", "ifrt.pjrt-execute", "                        cache_entry->executable->ifrt_executable()->Execute(", "interface", "fastpath 成立且动态 IFRT 实现是 PjRtLoadedExecutable；不经过 execute_sharded。"),
    ("jaxlib.execute-sharded", "jaxlib.execute-local", "  return ExecuteShardedOnLocalDevicesInternal(options, client_,", "direct", ""),
    ("jaxlib.execute-local", "ifrt.pjrt-execute", "    TF_ASSIGN_OR_RETURN(auto result, ifrt_loaded_executable->Execute(", "interface", "动态 IFRT 实现为 PjRtLoadedExecutable。"),
    ("ifrt.pjrt-execute", "pjrt.capi-execute", "                     pjrt_loaded_executable_->Execute(argument_handles, opts,", "interface", "非 portable；底层 provider 为 PjRtCApiLoadedExecutable。"),
    ("pjrt.capi-execute", "pjrt.capi-execute-args", "      GetCommonExecuteArgs(argument_handles, options, c_options,", "direct", ""),
    ("pjrt.capi-execute", "pjrt.c-execute-args", "      pjrt_c_api()->PJRT_LoadedExecutable_Execute(&args), pjrt_c_api());", "C API", "进入 plugin 函数指针；不声称真实 libtpu 内部使用开源 wrapper_impl。"),
    ("pjrt.capi-execute", "pjrt.event-to-future", "      device_complete_futures.push_back(pjrt::ConvertCEventToCppFuture(", "direct", "请求了设备完成事件。"),
    ("pjrt.event-to-future", "pjrt.event-callback-contract", "  PJRT_Error* error = c_api->PJRT_Event_OnReady(&event_onready_args);", "C API", "注册 host callback，回调错误状态与注册错误分开。"),
    ("jaxlib.array-wait", "jaxlib.buffers-wait", "    status = AwaitBuffersReady(absl::MakeConstSpan(&ifrt_array, 1));", "direct", "array 未删除。"),
    ("jaxlib.buffers-wait", "ifrt.array-ready", "    future = ifrt_arrays[0]->GetReadyFuture();", "interface", "单数组且实现为 PjRtArray。"),
    ("jaxlib.buffers-wait", "ifrt.values-ready", "    future = client->GetReadyFuture(values);", "interface", "多个数组且 client 为 PjRtClient。"),
    ("jaxlib.buffers-wait", "jaxlib.wait-with-signals", "  BlockUntilReadyWithCancel(future);", "direct", ""),
    ("ifrt.array-ready", "pjrt.buffer-ready-future", "    return pjrt_buffers_.front()->GetReadyFuture();", "interface", "一个本地 buffer 且 provider 为 C API buffer。"),
    ("pjrt.buffer-ready-future", "pjrt.buffer-track-event", "    MakePromiseTrackEvent();", "direct", "首次创建 readiness promise。"),
    ("pjrt.buffer-track-event", "pjrt.buffer-ready-event", "  is_ready_args.event = GetReadyEvent();", "direct", ""),
    ("pjrt.buffer-ready-event", "pjrt.buffer-ready-contract", "    pjrt::LogFatalIfPjrtError(api->PJRT_Buffer_ReadyEvent(&args), api);", "C API", "首次取得 cached ready event。"),
    ("pjrt.buffer-track-event", "pjrt.event-ready-contract", "      api->PJRT_Event_IsReady(&is_ready_args), pjrt::MakeErrorDeleter(api)};", "C API", "先查询 ready，包括失败终态。"),
    ("pjrt.buffer-track-event", "pjrt.event-callback-contract", "      api->PJRT_Event_OnReady(&args), ::pjrt::MakeErrorDeleter(api)};", "C API", "尚未 ready 时。"),
    ("jax.effects-barrier", "jax.runtime-tokens", "  dispatch.runtime_tokens.block_until_ready()", "direct", "当前线程局部 RuntimeTokenSet。"),
    ("jax.block-until-ready", "jaxlib.array-wait", "      return x.block_until_ready()", "interface", "leaf 是本例 PyArray；其他类型按 duck typing 处理。"),
    ("pjrt.capi-execute", "pjrt.profiler-link", "      pjrt::CreatePjrtProfilerExtension(", "direct", "提交给 plugin 的 linkage producer。"),
    ("pjrt.c-wrapper-execute", "pjrt.profiler-context", "  int64_t traceme_context_id = pjrt::GetTracemeContextId(args);", "direct", "仅开源 reference wrapper 的 Args extension 路径。"),
]
