"""Node content for the component-layout compile / execute overview.

Source-anchor names are verified by render_overview_software_stack_flows.py.
"""

# This mapping is the only source of core-concept labels and emphasis.
# CPU, GPU and TPU are separate modules inside the backend container.
CORE_CONCEPTS = {
    "jax": "outer",
    "jaxlib": "binding_module",
    "ifrt": "ifrt_array",
    "pjrt": "pjrt_buffer",
    "xla": "hlo",
    "cpu": "cpu_ir",
    "gpu": "gpu_ir",
    "tpu": "tpu_boundary",
    "asm": "asm",
    "runtime": "submit",
    "hardware": "isa",
}

NODES = {'function': {'tag': '产生 · 用户程序',
              'title': 'Python 函数 + 抽象输入',
              'rows': ['函数、静态参数、avals 与分片信息参与追踪。', 'jit / grad / vmap 等变换组合程序语义。', '实际数据在执行通路中传递。'],
              'refs': ('trace_to_jaxpr_dynamic',)},
 'outer': {'tag': '外层程序',
           'title': 'Jaxpr',
           'rows': ['JaxprEqn 记录 Primitive、参数与 effects。',
                    'pallas_call 是外层方程之一。',
                    'eqn.params 携带 kernel Jaxpr + GridMapping。',
                    '方程的 invars / outvars 连接外层数据流。'],
           'refs': ('Jaxpr', 'pallas_call_p.bind')},
 'kernel': {'tag': '程序结构 · Pallas 内层程序',
            'title': 'kernel Jaxpr + GridMapping',
            'rows': ['独立追踪 kernel；Ref 读写表达块内计算。',
                     'GridMapping 描述网格、块与调用约定。',
                     '由 pallas_call 方程参数携带到 lowering。'],
            'refs': ('_trace_kernel_to_jaxpr', 'GridMapping')},
 'inputs': {'tag': '数据入口',
            'title': '主机值 / jax.Array',
            'rows': ['input handler 处理实参数组与分片布局。', '必要时放置、复制或重分片。', '进入 ExecuteSharded 时使用 PyArray 参数。'],
            'refs': ('ExecuteReplicated',),
            'color': 'data'},
 'transforms': {'tag': '变换 · Jaxpr → Jaxpr',
                'title': '组合变换与程序整理',
                'rows': ['追踪规则、自动微分、批处理与部分求值。', 'Jaxpr 变换可重写方程、变量和 effects。', '例如 dce_jaxpr 删除未消费的纯计算。'],
                'refs': ('dce_jaxpr',),
                'color': 'transform'},
 'lower': {'tag': '消费 Jaxpr · 产生 MLIR',
           'title': 'lower_jaxpr_to_module',
           'rows': ['jaxpr_subcomp 遍历方程并调用 lowering 规则。',
                    '普通方程生成外层操作；Pallas 按平台分派。',
                    'Mosaic TPU 分支：interpret=False。'],
           'refs': ('lower_jaxpr_to_module', 'jaxpr_subcomp', '_pallas_call_lowering')},
 'mosaic': {'tag': '消费 kernel · 独立模块',
            'title': 'Mosaic TPU MLIR Module',
            'rows': ['TPU lowering 消费 kernel Jaxpr 和 GridMapping。',
                     'lower_jaxpr_to_pipelined_module 构造模块。',
                     '该模块随后封装入外层 custom_call。'],
            'refs': ('pallas_call_tpu_lowering_rule', 'lower_jaxpr_to_pipelined_module')},
 'dispatch': {'tag': '消费可执行对象与输入',
              'title': 'ExecuteReplicated.__call__',
              'rows': ['in_handler(args) → 输入 PyArray 序列。',
                       'xla_executable.execute_sharded(input_bufs)。',
                       '处理 effects / tokens 与结果 handlers。'],
              'refs': ('ExecuteReplicated',),
              'color': 'data'},
 'shardy': {'tag': '变换 · 按配置启用',
            'title': 'Shardy 的模块 pass',
            'rows': ['JAX lowering 中可运行 sdy-lift-inlined-meshes。',
                     '输入和输出都是外层 MLIR Module。',
                     '分片表示及其处理依配置和编译阶段而定。'],
            'refs': ('Shardy module pass',),
            'color': 'transform'},
 'module': {'tag': 'lowering 产物 · 编译提交对象',
            'title': '外层 MLIR Module',
            'rows': ['函数、类型与 StableHLO / 配套方言操作。',
                     '可同时包含普通算子与 stablehlo.custom_call。',
                     'custom_call 的结果值继续连接外层 IR。',
                     'Module + CompileOptions 交给后端编译。'],
            'refs': ('lower_jaxpr_to_module',)},
 'payload': {'tag': '回接外层 · 编译期数据',
             'title': 'tpu_custom_call + Mosaic payload',
             'rows': ['模块经 pass / 版本化序列化产生 payload。',
                      'backend_config 携带 payload 与调用配置。',
                      '构造 stablehlo.custom_call，返回 IR 结果值。'],
             'refs': ('lower_module_to_custom_call', 'emit tpu_custom_call'),
             'detail': '../jax/jaxpr-centered-hub.svg#inner_jaxpr'},
 'outputs': {'tag': 'Python 可见输出',
             'title': 'jax.Array / PyArray',
             'rows': ['结果按 aval、sharding 与 handler 组织。',
                      '数组对象持有 IFRT Array；可异步就绪。',
                      '需要等待时显式查询 / 阻塞就绪状态。'],
             'refs': ('ConsumeWithHandlers',),
             'color': 'output'},
 'py_loaded': {'tag': '编译返回 · Python 对象',
               'title': 'PyLoadedExecutable',
               'rows': ['Await IFRT 的编译结果，再构造 Python 包装。',
                        '持有 ifrt::LoadedExecutableRef。',
                        '随后由 ExecuteReplicated 调用执行方法。'],
               'refs': ('PyLoadedExecutable wrapping',),
               'color': 'result'},
 'py_compile': {'tag': '编译调用 · 绑定入口',
                'title': 'PyClient::CompileAndLoad',
                'rows': ['输入：mlir::ModuleOp + xla::CompileOptions。',
                         '克隆 Module，构造 ifrt::HloProgram。',
                         'MakeIfrtCompileOptions 包装选项。',
                         '经 GetDefaultCompiler() 发起编译。'],
                'refs': ('PyClient.CompileAndLoad', 'IFRT CompileAndLoad')},
 'py_execute': {'tag': '执行调用 · 数组参数',
                'title': 'PyLoadedExecutable::ExecuteSharded',
                'rows': ['输入：PyArray 序列与执行选项。',
                         '从 arg.ifrt_array() 取得 ArrayRef。',
                         '调用 IFRT LoadedExecutable::Execute。',
                         '返回 PyExecuteResults；供结果 handler 消费。'],
                'refs': ('ExecuteSharded',),
                'color': 'data'},
 'py_outputs': {'tag': '输出返回 · 原生到 Python',
                'title': 'PyExecuteResults → PyArray',
                'rows': ['接收 IFRT outputs，保留需要的 status。',
                         'consume_with_handlers 调用结果处理器。',
                         'PyArray 包装 IFRT Array 与 Python 元信息。',
                         '此处完成数组对象的 Python 层构造。'],
                'refs': ('ConsumeWithHandlers',),
                'color': 'output'},
 'ifrt_loaded': {'tag': '编译返回 · IFRT 对象',
                 'title': 'ifrt::LoadedExecutable',
                 'rows': ['PJRT-backed 实现包装 PjRtLoadedExecutable。',
                          '附带输出 dtype / shape / sharding / layout。',
                          '以 LoadedExecutableRef 返回上层。'],
                 'refs': ('IFRT executable wrapping',),
                 'color': 'result'},
 'ifrt_compile': {'tag': '编译调用 · 框架接口',
                  'title': 'Compiler::CompileAndLoad',
                  'rows': ['输入：HloProgram + IFRT CompileOptions。',
                           'HloProgram 承载外层 MLIR Module。',
                           'PJRT 适配实现取出 Module 和 XLA 选项。',
                           '将编译请求委托给 PjRtClient。'],
                  'refs': ('IFRT CompileAndLoad', 'PJRT CompileAndLoad')},
 'ifrt_execute': {'tag': '执行调用 · 逻辑数组',
                  'title': 'LoadedExecutable::Execute',
                  'rows': ['输入：ArrayRef[] + options + 可选 devices。',
                           '适配层验证设备、分片与参数数量。',
                           '从 PJRT-backed Array 取得各分片 Buffer。',
                           '按计算 / 设备组织 PjRtBuffer* 参数。'],
                  'refs': ('IFRT Execute', 'ifrt Array'),
                  'color': 'data'},
 'ifrt_outputs': {'tag': '输出返回 · 逻辑数组',
                  'title': 'ExecuteResult / PjRtArray',
                  'rows': ['按输出聚合各计算返回的 PjRtBuffer。',
                           'PjRtArray::Create 加入 shape / sharding 等。',
                           'result.outputs 为 ArrayRef[]。',
                           '仅 fill_status=true 时填充 result.status。'],
                  'refs': ('IFRT output arrays', 'IFRT ExecuteResult'),
                  'color': 'output'},
 'pjrt_loaded': {'tag': '编译返回 · provider 装载与包装',
                 'title': 'xla::PjRtLoadedExecutable',
                 'rows': ['CPU：CpuExecutable → PjRtCpuExecutable。',
                          'LoadInternal 再构造 PjRtCpuLoadedExecutable。',
                          'GPU / TPU 由各自 provider 实现加载与包装。',
                          '返回具体实现对象，经 PJRT 公共接口访问。',
                          '后续 Execute 使用已加载程序与设备映射。'],
                 'refs': ('CPU executable wrapping', 'CPU LoadInternal'),
                 'color': 'result'},
 'pjrt_compile': {'tag': '编译调用 · provider 分派',
                  'title': 'PjRtClient::CompileAndLoad',
                  'rows': ['输入：Module + xla::CompileOptions。',
                           'CPU/GPU → 公开 XLA 编译链。',
                           'TPU → TPU provider / libtpu 公开接口边界。',
                           '编译产物再经 provider 加载为可执行对象。',
                           '本图展开 CompileAndLoad 路径。'],
                  'refs': ('PJRT CompileAndLoad',)},
 'pjrt_execute': {'tag': '执行调用 · 设备分片存储',
                  'title': 'PjRtLoadedExecutable::Execute',
                  'rows': ['输入：按计算组织的 PjRtBuffer* 二维序列。',
                           '选项包含 donation 等执行约束。',
                           'provider 消费已加载程序、输入存储与依赖。',
                           '下方的机制取决于后端实现。',
                           '可请求每个计算的完成 future。'],
                  'refs': ('PjRtLoadedExecutable Execute',),
                  'color': 'data'},
 'pjrt_outputs': {'tag': '输出返回 · 设备 Buffer',
                  'title': 'PjRtBuffer[][] + 完成 future',
                  'rows': ['Execute 返回各计算 / 各输出的 Buffer。',
                           'Buffer 关联设备、内存空间、形状与生命周期。',
                           '上层按输出维度重新聚合这些分片。',
                           'Buffer::GetReadyFuture 查询数据可用状态。',
                           '取得 Buffer 对象与数据就绪是不同事件。'],
                  'refs': ('PjRtBuffer', 'PJRT Buffer readiness'),
                  'color': 'output'},
 'import': {'tag': '产生 HLO · 公开 CPU/GPU 路径',
            'title': 'MLIR / StableHLO → HLO',
            'rows': ['provider 将输入 Module 接入 XLA 编译。',
                     '导入建立 HloModule 与编译配置。',
                     '外层 custom call 仍有其目标与配置。'],
            'refs': ('MLIR to HLO',)},
 'hlo': {'tag': 'XLA 程序',
         'title': 'HLO（HloModule）',
         'rows': ['HloComputation / HloInstruction 表达计算图。',
                  'shape、layout、分片、配置共同约束语义。',
                  '后续 pipeline 重写这一程序表示。'],
         'refs': ('HloModule',)},
 'passes': {'tag': '变换 · 编译优化',
            'title': 'HLO pass pipeline',
            'rows': ['规范化、代数重写、融合、分片与目标优化。',
                     'RunHloPasses 等阶段消费并更新 HloModule。',
                     '具体顺序与目标、选项和编译阶段相关。',
                     '优化后的 HLO 供后端规划与代码生成。'],
            'refs': ('CPU JitCompile', 'HloPassPipeline RunImpl')},
 'plan': {'tag': '规划 · HLO 到目标执行',
          'title': '调度 / BufferAssignment',
          'rows': ['确定执行顺序、布局和存储分配等约束。',
                   'BufferAssignment 将 HLO 值映射到分配切片。',
                   '它是编译期规划；运行时 Buffer 承载实际存储。',
                   '规划阶段与代码生成由目标后端组织。'],
          'refs': ('BufferAssignment',)},
 'cpu': {'tag': 'XLA CPU 后端 · 消费 HLO / 规划',
         'title': 'LLVM IR → CPU 目标代码',
         'rows': ['RunBackend 组织 lowering、LLVM 优化与编译。',
                  '生成代码及 CPU 执行所需的计划与元数据。',
                  '结合运行时任务、thunk 或库实现计算。',
                  '产出 CpuExecutable，交回 provider。'],
         'refs': ('CPU RunBackend',),
         'detail': '../xla/cpu-llvm-ir-centered-hub.svg'},
 'gpu': {'tag': 'XLA GPU 后端 · 多种实现路径',
         'title': 'LLVM / Triton / 设备库',
         'rows': ['按目标选择 emitter、Triton 或库调用路径。',
                  '代码生成可产生 LLVM IR、PTX / 目标二进制。',
                  '库调用保留在执行计划中，不必生成自有 kernel。',
                  'GpuExecutable 汇集目标代码和执行计划。'],
         'refs': ('GPU RunBackend',),
         'detail': '../xla/gpu-ir-centered-hub.svg'},
 'executable': {'tag': '编译产物 · 返回链起点',
                'title': 'XLA Executable + 执行计划',
                'rows': ['CPU/GPU 的目标代码、入口与执行调度信息。',
                         '保留 BufferAssignment、结果布局等元数据。',
                         'CPU 实例：CpuExecutable → PjRtCpuExecutable。',
                         'provider 进一步加载并附加设备映射与状态。',
                         '沿左侧橙线返回 PJRT → IFRT → Python。',
                         '此产物节点与下方 ASM 观察节点分开。'],
                'refs': ('XLA Executable', 'CPU executable wrapping'),
                'color': 'result'},
 'tpu': {'tag': 'TPU provider / libtpu · 公开边界',
         'title': 'Module → PjRtLoadedExecutable',
         'rows': ['输入仍是外层程序，可能携带 Mosaic payload。',
                  '公开接口允许编译 / 加载和设备执行。',
                  '返回对象由 provider 实现 PJRT 接口。',
                  '未据此确认私有 IR、pass 或内部产物布局。',
                  'Mosaic TPU MLIR 不等同于 LLO。',
                  '棕色连线仅标出该 provider 的输入边界。'],
         'color': 'unknown',
         'detail': '../libtpu/llo-boundary-centered-hub.svg'},
 'asm': {'tag': '可观察表示 · 编译产物侧视图',
         'title': 'ASM / 反汇编 / 目标代码',
         'rows': ['CPU 汇编、GPU PTX 或目标二进制可用于观察代码生成；库实现与实际装载路径需另行核对。', 'ASM 是程序表示，不是每条执行路径都必须经过的独立软件组件。'],
         'color': 'neutral'},
 'submit': {'tag': '消费 · 程序和数据汇合',
            'title': '执行提交',
            'rows': ['provider 的执行实现读取入口、执行计划与参数。',
                     '准备输出存储、donation / alias 与数据依赖。',
                     '调度计算，并建立输出句柄及其就绪状态。',
                     '输出句柄可先于设备计算完成返回。'],
            'refs': ('PjRtLoadedExecutable Execute',),
            'color': 'data'},
 'handles': {'tag': '输出对象的产生',
             'title': '存储句柄与依赖跟踪',
             'rows': ['provider 将输出存储包装成 PjRtBuffer。',
                      'Buffer 持有该输出的数据就绪状态。',
                      '上方继续包装 IFRT Array 和 Python PyArray。',
                      '具体输出就绪时序取决于后端。'],
             'refs': ('PJRT Buffer readiness', 'IFRT ExecuteResult'),
             'color': 'output'},
 'runtime': {'tag': '执行机制 · 各后端分别实现',
             'title': '任务 / kernel / 库 / provider',
             'rows': ['CPU：任务 / thunk 与主机代码、库调用。',
                      'GPU：StreamExecutor、stream、kernel / 库。',
                      'CUDA 路径继续调用驱动的提交接口。',
                      'TPU：provider 管理程序提交和设备依赖。',
                      '并非所有后端都经过 CUDA / StreamExecutor。',
                      '设备工作及依赖完成后更新相应就绪状态。'],
             'refs': ('CPU runtime Execute',),
             'color': 'data',
             'detail': '../stream-executor/submission-centered-hub.svg'},
 'runtime_completion': {'tag': '状态事件 · 与对象包装分开',
                'title': '完成、错误与 Future',
                'rows': ['设备事件 / 后端状态驱动输出数据就绪。',
                         'PjRtBuffer::GetReadyFuture 可查询此状态。',
                         'Execute 的 returned futures 表示执行完成。',
                         'IFRT 适配层可聚合这些 future。',
                         'ExecuteResult.status 仅按 fill_status 填充。',
                         '异步完成不要求重建已有 Array / PyArray。'],
                'refs': ('PJRT Buffer readiness', 'IFRT ExecuteResult'),
                'color': 'output'},
 'hardware': {'tag': '执行 · 物理设备',
              'title': 'CPU / GPU / TPU 执行单元',
              'rows': ['处理目标工作、读写存储并产生完成事件。',
                       'CPU 主机任务、GPU kernel 与 TPU 设备程序。',
                       '计算、通信与传输按后端依赖协作。',
                       '具体资源、指令和时序取决于目标硬件。'],
              'color': 'data'},
 'isa': {'tag': '契约 · 目标相关',
         'title': 'ISA',
         'rows': ['规定指令的操作、编码与可见行为。',
                  '内存模型与 ABI 补充存储和调用约束。',
                  '编译器生成代码，运行时满足执行约定。',
                  'TPU 私有指令 / IR 不在本图中推断。',
                  'ASM 可辅助观察，不能替代执行证据。'],
         'color': 'neutral'},
 'memory': {'tag': '存储与通信',
            'title': '主机 / 设备内存、传输与同步',
            'rows': ['Buffer 指向特定设备或内存空间的存储；Array 是其上层逻辑视图。',
                     '数据搬运、跨设备通信、stream / task 依赖与生命周期由相应后端管理。',
                     '本图为源码结构图；没有据此声称完成 CPU、TPU 模拟、离线 TPU 编译或真实 TPU 执行。'],
            'color': 'neutral'}}

NODES.update({
    "trace": {
        "tag": "产生 · tracing", "title": "Trace / Tracer",
        "rows": ["Tracer 携带 aval；Trace 解释原语操作。", "动态追踪收集方程并构造 Jaxpr。", "Python 函数与抽象输入共同决定追踪结果。"],
        "refs": ("trace_to_jaxpr_dynamic",),
    },
    "values": {
        "tag": "定义 · 值与约束", "title": "Var / Literal / aval",
        "rows": ["变量引用与字面值构成方程的输入和输出。", "aval 表达形状、dtype 等抽象类型。", "Jaxpr 将参数、常量、结果与方程组织为程序。"],
        "refs": ("Var", "Jaxpr"),
    },
    "binding_module": {
        "tag": "编译输入表示", "title": "MLIR Module（StableHLO）",
        "rows": ["jaxlib 绑定提供 Module / Operation / Type。", "StableHLO 等方言规定操作语义。", "外层 Module 可含普通操作和 custom_call。", "PyClient 克隆并包装 Module 后提交编译。"],
        "refs": ("StableHLO binding", "PyClient.CompileAndLoad"),
    },
    "py_array": {
        "tag": "数据包装 · Python 数组", "title": "PyArray",
        "rows": ["Python 数组对象持有 IFRT Array 引用。", "附带 aval、sharding 等 Python 侧元信息。", "ExecuteSharded 从输入 PyArray 取出 ArrayRef。"],
        "refs": ("PyArray", "ExecuteSharded"), "color": "data",
    },
    "ifrt_program": {
        "tag": "编译输入 · Program 实现", "title": "HloProgram",
        "rows": ["在此路径中承载外层 MLIR Module。", "名称不表示已转换成 XLA HloModule。", "Compiler 接收 Program 和 IFRT 编译选项。"],
        "refs": ("PyClient.CompileAndLoad",),
    },
    "ifrt_array": {
        "tag": "逻辑数组", "title": "Array",
        "rows": ["dtype / shape / sharding 描述逻辑数组。", "Sharding / DeviceList 约束分片与设备。", "PJRT-backed Array 管理底层 PjRtBuffer。", "Array → Buffer 是实现映射与参数解包。"],
        "refs": ("ifrt Array", "IFRT Execute"), "color": "data",
    },
    "pjrt_buffer": {
        "tag": "设备存储", "title": "PjRtBuffer",
        "rows": ["Buffer 关联 shape、Device 与 MemorySpace。", "接口管理存储生命周期、所有权与就绪。", "Execute 消费各设备上的 Buffer 实参。", "GetReadyFuture 表达数据可用状态。"],
        "refs": ("PjRtBuffer", "PJRT Buffer readiness"), "color": "data",
    },
    "provider": {
        "tag": "具体实现 / 插件边界", "title": "Backend provider",
        "rows": ["实现 PjRtClient 的编译、加载与执行行为。", "CPU/GPU 路径调用公开 XLA 编译实现。", "TPU 请求进入 provider / libtpu 边界。", "provider 包装产物并返回 PjRtLoadedExecutable。"],
        "refs": ("CPU Module compilation", "CPU LoadInternal"),
    },
    "hlo_structure": {
        "tag": "定义 · HLO 程序结构", "title": "Computation / Instruction",
        "rows": ["HloModule 持有入口与嵌套计算。", "HloComputation 包含指令及根结果。", "operand / user 关系表达数据依赖。", "shape、layout、分片和配置约束程序。"],
        "refs": ("HloModule",),
    },
    "cpu_lowering": {
        "tag": "输入与选择 · XLA CPU", "title": "HLO / emitter / RunBackend",
        "rows": ["消费目标 HLO 与编译规划。", "后端组织 lowering、优化和代码生成。", "为函数、kernel 与运行时调用构造低层程序。"],
        "refs": ("CPU RunBackend",),
    },
    "cpu_ir": {
        "tag": "XLA CPU 表示", "title": "LLVM IR",
        "rows": ["Module / Function / BasicBlock 组织程序。", "Instruction 表达低层计算与控制流。", "LLVM 优化、目标代码生成与链接消费该表示。"],
        "refs": ("CPU RunBackend",),
        "detail": "../xla/cpu-llvm-ir-centered-hub.svg",
    },
    "gpu_lowering": {
        "tag": "输入与选择 · XLA GPU", "title": "原生 emitter / Triton / 库",
        "rows": ["按计算特征和目标选择适用实现。", "Triton 路径还涉及相应方言表示。", "代码生成与设备库调用可以并存。", "库调用直接进入执行计划中的相应调用。"],
        "refs": ("GPU RunBackend",),
    },
    "gpu_ir": {
        "tag": "XLA GPU 表示", "title": "LLVM IR",
        "rows": ["Module / Function 组织低层设备程序。", "LLVM 优化与目标代码生成消费该表示。", "本图以此为中心展开 GPU 代码生成路径。", "设备库调用可绕过此 IR 节点。"],
        "refs": ("GPU RunBackend",),
        "detail": "../xla/gpu-ir-centered-hub.svg",
    },
    "tpu_boundary": {
        "tag": "私有阶段的证据边界", "title": "LLO（待版本证据）",
        "rows": ["公开提交接口不能证明内部 IR 的结构。", "内部 passes、转换位置与产物布局待确认。", "Mosaic TPU MLIR 不能据此称为 LLO。", "此节点说明未知范围，不表示已确认的转换阶段。"],
        "color": "unknown", "dashed": True,
        "detail": "../libtpu/llo-boundary-centered-hub.svg",
    },
    "tpu_loaded": {
        "tag": "公开返回边界 · provider 实现", "title": "TPU 的 PjRtLoadedExecutable",
        "rows": ["provider 通过 PJRT 接口返回可执行对象。", "实现编译产物加载、设备关联和执行接口。", "上层继续包装成 IFRT / Python 可执行对象。"],
        "refs": ("PjRtLoadedExecutable",), "color": "unknown", "dashed": True,
    },
    "asm_code": {
        "tag": "编译产物 · 可观察的目标代码", "title": "目标代码 / 对象文件",
        "rows": ["CPU 目标代码或 GPU 目标二进制。", "可按需 dump 或经反汇编查看。", "编译过程未必保留可读汇编文本。"],
        "color": "neutral",
    },
    "asm_tools": {
        "tag": "消费 · 诊断与检查", "title": "汇编器 / 反汇编 / 检查工具",
        "rows": ["读取目标表示，辅助理解与诊断代码生成。", "文本可被汇编，目标代码也可被反汇编。", "可见形式与平台、工具及编译选项相关。"],
        "color": "neutral",
    },
    "runtime_program": {
        "tag": "编译通路交付", "title": "已加载程序 / 执行计划",
        "rows": ["已加载代码、入口、常量和调度信息。", "具体对象及其生命周期由 provider 管理。", "执行实现消费这些信息与本次输入实参。"],
        "refs": ("PjRtLoadedExecutable",), "color": "program",
    },
    "runtime_buffers": {
        "tag": "数据通路交付", "title": "输入 Buffer / 执行依赖",
        "rows": ["设备实参及其数据可用条件。", "donation、alias 和放置需满足执行约束。", "后端按输入状态组织任务和设备依赖。"],
        "refs": ("PjRtLoadedExecutable Execute",), "color": "data",
    },
})

NODES["cpu"].update(tag="消费 / 产物 · XLA CPU", title="CpuExecutable / CPU 目标代码",
    rows=["LLVM 编译与链接得到目标代码。", "结合任务、thunk 或库实现计算。", "CpuExecutable 集成代码、内存与执行计划。", "返回 XLA 产物节点，再交 provider 包装。"])
NODES["gpu"].update(tag="消费 / 产物 · XLA GPU", title="GpuExecutable / 代码与库调用",
    rows=["目标代码与库调用共同组成执行计划。", "NVIDIA 路径可生成 PTX / 目标二进制。", "GpuExecutable 汇集代码、元数据和执行计划。", "库调用保留旁路，不必生成自有 kernel。"])
NODES["tpu"].update(tag="输入边界 · TPU provider / libtpu", title="外层 Module + 可选 Mosaic payload",
    rows=["接收 Module + CompileOptions。", "外层 custom_call 可携带 Mosaic kernel payload。", "公开接口支持编译 / 加载；内部过程保持不透明。"], dashed=True)
NODES["asm"].update(tag="可观察表示", title="ASM",
    rows=["助记符、寄存器与地址等形式表达目标程序。", "是程序表示或观察形式，不是独立运行时组件。", "不将 ASM → ISA 画成每条路径的强制转换。"])
NODES["memory"].update(title="寄存器 / 内存 / 互连",
    rows=["承载输入、临时值和输出数据。", "计算、传输与通信遵循相应设备依赖。", "Buffer 是存储接口，Array 是上层逻辑视图。"])
NODES["executable"]["rows"][4] = "经 R0 → R1 → R2 返回 PJRT / IFRT / Python。"
NODES["asm"]["color"] = "program"
NODES["isa"].update(tag="指令语义契约", color="program")
